module.exports = {
	content: ['./src/**/*.{js,jsx,ts,tsx,json}'],
	theme: {
		extend: {
			backgroundImage: {
				bgPokemon: "url('/src/assets/bgPokemon.svg')",
				bgHome: "url('/src/assets/bg/bgHome.svg')",
				SearchIcon: "url('/src/assets/icons/Search.svg')",
				PokemonCard: "url('/src/assets/bg/Pokeball.svg')",
				BugIcon: "url('/src/assets/pokemonTypeIcon/Bug.svg')",
				DarkIcon: "url('/src/assets/pokemonTypeIcon/Dark.svg')",
				DragonIcon: "url('/src/assets/pokemonTypeIcon/Dragon.svg')",
				ElectricIcon: "url('/src/assets/pokemonTypeIcon/Electric.svg')",
				FairyIcon: "url('/src/assets/pokemonTypeIcon/Fairy.svg')",
				FightingIcon: "url('/src/assets/pokemonTypeIcon/Fighting.svg')",
				FireIcon: "url('/src/assets/pokemonTypeIcon/Fire.svg')",
				FlyingIcon: "url('/src/assets/pokemonTypeIcon/Flying.svg')",
				GhostIcon: "url('/src/assets/pokemonTypeIcon/Ghost.svg')",
				GrassIcon: "url('/src/assets/pokemonTypeIcon/Grass.svg')",
				GroundIcon: "url('/src/assets/pokemonTypeIcon/Ground.svg')",
				IceIcon: "url('/src/assets/pokemonTypeIcon/Ice.svg')",
				NormalIcon: "url('/src/assets/pokemonTypeIcon/Normal.svg')",
				PoisonIcon: "url('/src/assets/pokemonTypeIcon/Poison.svg')",
				PsychicIcon: "url('/src/assets/pokemonTypeIcon/Psychic.svg')",
				RockIcon: "url('/src/assets/pokemonTypeIcon/Rock.svg')",
				SteelIcon: "url('/src/assets/pokemonTypeIcon/Steel.svg')",
				WaterIcon: "url('/src/assets/pokemonTypeIcon/Water.svg')",
			},
		},
	},
	plugins: [],
};
